version: '3.7'

services:
  medre-be:
    build: .
    image: medre-be
    container_name: medre-src
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_SYNC=0
    ports:
      - '6543:6543'
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/medre-be
    networks:
      - medre-be-network

  postgres:
    image: postgres
    container_name: medre-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - medre-db:/data/db
    networks:
      - medre-be-network

volumes:
  medre-db:

networks:
  medre-be-network:
    driver: bridge
